// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppPS.Models;

namespace WebAppPS.Migrations
{
    [DbContext(typeof(RekrutacjaContext))]
    partial class RekrutacjaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Polish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppPS.Entity.Weryfikacja", b =>
                {
                    b.Property<DateTime?>("DataWysz")
                        .HasColumnType("datetime");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Weryfikacja1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("Weryfikacja")
                        .IsFixedLength(true);

                    b.Property<string>("WyszNip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.ToTable("Weryfikacja");
                });

            modelBuilder.Entity("WebAppPS.Models.Klienci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataDodania")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataPodpisaniaUmowy")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("LimitNaUmowie")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("NazwaPelna")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NazwaSkrocona")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NumerUmowy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Profil")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("klienci");
                });

            modelBuilder.Entity("WebAppPS.Models.KlienciKontrahenci", b =>
                {
                    b.Property<int>("IdKlienta")
                        .HasColumnType("int");

                    b.Property<int>("IdKontrahenta")
                        .HasColumnType("int");

                    b.Property<decimal?>("LimitNaUmowie")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdKlienta", "IdKontrahenta")
                        .HasName("PK__klienci___25DE50FD09E17413");

                    b.HasIndex("IdKontrahenta");

                    b.ToTable("klienci_kontrahenci");
                });

            modelBuilder.Entity("WebAppPS.Models.KlienciKontrahenci", b =>
                {
                    b.HasOne("WebAppPS.Models.Klienci", "IdKlientaNavigation")
                        .WithMany("KlienciKontrahenciIdKlientaNavigations")
                        .HasForeignKey("IdKlienta")
                        .HasConstraintName("FK__klienci_k__IdKli__267ABA7A")
                        .IsRequired();

                    b.HasOne("WebAppPS.Models.Klienci", "IdKontrahentaNavigation")
                        .WithMany("KlienciKontrahenciIdKontrahentaNavigations")
                        .HasForeignKey("IdKontrahenta")
                        .HasConstraintName("FK__klienci_k__IdKon__276EDEB3")
                        .IsRequired();

                    b.Navigation("IdKlientaNavigation");

                    b.Navigation("IdKontrahentaNavigation");
                });

            modelBuilder.Entity("WebAppPS.Models.Klienci", b =>
                {
                    b.Navigation("KlienciKontrahenciIdKlientaNavigations");

                    b.Navigation("KlienciKontrahenciIdKontrahentaNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
